# For puppetlabs_spec_helper documentation - see https://github.com/puppetlabs/puppetlabs_spec_helper

fixtures:
  repositories:
    stdlib: 'git://github.com/puppetlabs/puppetlabs-stdlib'
  symlinks:
    samples/files: '../../../../files'
    samples/manifests: '../../../../manifests'
    samples/templates: '../../../../templates'
