# For puppetlabs_spec_helper documentation - see https://github.com/puppetlabs/puppetlabs_spec_helper

fixtures:
  repositories:
    stdlib: 'git://github.com/puppetlabs/puppetlabs-stdlib'
    puppet: 'git://github.com/abstractitptyltd/abstractit-puppet'
    firewall: 'https://github.com/puppetlabs/puppetlabs-firewall.git'
    apache: 'https://github.com/puppetlabs/puppetlabs-apache.git'
    concat: 'https://github.com/puppetlabs/puppetlabs-concat.git'
    mysql: 'https://github.com/puppetlabs/puppetlabs-mysql.git'
    vsftpd: 'https://github.com/thias/puppet-vsftpd.git'
    wordpress: 'https://github.com/boonchu/puppet-wordpress.git'
  symlinks:
    samples/files: '../../../../files'
    samples/manifests: '../../../../manifests'
    samples/templates: '../../../../templates'
