# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.require_version ">= 1.8.0"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Using Puppet Labs official vagrant boxes, from: https://vagrantcloud.com/puppetlabs
  config.vm.box = "centos7-puppet3.8.1"

  config.vm.provision :shell, :path => "./.vagrant_puppet/init.sh"

  config.vm.provider 'virtualbox' do |vbox|
    vbox.memory = 1024
    vbox.cpus = 2
  end

  config.vm.provision :puppet do |puppet|
    puppet.environment_path = '.vagrant_puppet/environments'
    puppet.environment = 'vagrant'
    puppet.options = '--verbose'
    puppet.hiera_config_path = 'hiera/hiera.yaml'    
  end

  config.vm.provision :serverspec do |spec|
    spec.pattern = 'serverspec/*_spec.rb'
  end

end

# need serverspec
# vagrant plugin install vagrant-serverspec
unless Vagrant.has_plugin?('vagrant-serverspec')
  raise 'vagrant-serverspec is not installed!'
end
